import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@parkify/ui/src/app/globals.css'
import { MenuItem } from '@parkify/util/types'
import { ApolloProvider } from '@parkify/network/src/config/apollo'
import { SessionProvider } from '@parkify/ui/src/components/molecules/SessionProvider'
import { ToastContainer } from '@parkify/ui/src/components/molecules/Toast'
import { Container } from '@parkify/ui/src/components/atoms/Container'
import { Header } from '@parkify/ui/src/components/organisms/Header'
import { IsAdmin } from '@parkify/ui/src/components/organisms/IsAdmin'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parkify | Admin',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Garages', href: '/' },
  { label: 'Admins', href: '/manageAdmins' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-25`}>
        <SessionProvider>
          <ApolloProvider>
            <Header type="admin" menuItems={MENUITEMS} />
            <Container>{children}</Container>
          </ApolloProvider>
        </SessionProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
